# Generated by Django 5.1.7 on 2025-03-16 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'BPS'), (2, 'Disdukcapil')])),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year for BPS data.', null=True)),
                ('fetched_at', models.DateField(blank=True, help_text='Date when Disdukcapil data was fetched.', null=True)),
                ('male_count', models.PositiveBigIntegerField(help_text='Male population count.')),
                ('female_count', models.PositiveBigIntegerField(help_text='Female population count.')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='regions.village')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'year'], name='demographic_source_29f915_idx'),
                            models.Index(fields=['source', 'fetched_at'], name='demographic_source_c732ca_idx')],
                'unique_together': {('village', 'source', 'fetched_at'), ('village', 'source', 'year')},
            },
        ),
    ]
