# Generated by Django 5.1.7 on 2025-03-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Kecamatan'), (2, 'Distrik')])),
                ('capital_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('iso_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('capital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('legal_basis', models.CharField(blank=True, max_length=255, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('geographical_unit', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='provinces',
                    to='regions.geographicunit')),
            ],
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('sni_code', models.CharField(blank=True, max_length=3, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(
                    choices=[(1, 'Kabupaten'), (2, 'Kota'), (3, 'Kabupaten Administratif'),
                             (4, 'Kota Administratif')])),
                ('capital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('legal_basis', models.CharField(blank=True, max_length=255, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('vehicle_plate_prefix', models.CharField(
                    blank=True, help_text="The optional prefix of the plate number (e.g., 'AB', 'BC', 'CD').",
                    max_length=2, null=True)),
                ('vehicle_plate_suffix', models.CharField(
                    blank=True, help_text="The optional suffix of the plate number (e.g., 'D', 'V', 'Z').",
                    max_length=50, null=True)),
                ('capital', models.ForeignKey(
                    blank=True, help_text='Optional reference if the capital is a district.', null=True,
                    on_delete=django.db.models.deletion.SET_NULL, related_name='regency_capitals',
                    to='regions.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='regencies', to='regions.province')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='capital',
            field=models.ForeignKey(
                blank=True, help_text='Optional reference if the capital is a regency/city.', null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='province_capitals', to='regions.regency'),
        ),
        migrations.AddField(
            model_name='district',
            name='regency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='regions.regency'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Desa'), (2, 'Kelurahan')])),
                ('gis_area', models.DecimalField(
                    blank=True, decimal_places=2, help_text='Area in square kilometers from GIS data.',
                    max_digits=10, null=True)),
                ('bps_area', models.DecimalField(
                    blank=True, decimal_places=2, help_text='Area in square kilometers from BPS data.',
                    max_digits=10, null=True)),
                ('district', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='villages',
                    to='regions.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='capital',
            field=models.ForeignKey(
                blank=True, help_text='Optional reference if the capital is a village.',
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_capitals',
                to='regions.village'),
        ),
    ]
