# Generated by Django 5.1.7 on 2025-04-03 02:41

import geoindodata.core.utils
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_province_motto_language_province_motto_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='coat_of_arms',
            field=thumbnails.fields.ImageField(
                blank=True, null=True,
                upload_to=geoindodata.core.utils.FilenameGenerator(prefix='provinces')),
        ),
        migrations.AddField(
            model_name='province',
            name='flag',
            field=thumbnails.fields.ImageField(
                blank=True, null=True,
                upload_to=geoindodata.core.utils.FilenameGenerator(prefix='provinces')),
        ),
        migrations.AddField(
            model_name='regency',
            name='coat_of_arms',
            field=thumbnails.fields.ImageField(
                blank=True, null=True,
                upload_to=geoindodata.core.utils.FilenameGenerator(prefix='regencies')),
        ),
        migrations.AddField(
            model_name='regency',
            name='flag',
            field=thumbnails.fields.ImageField(
                blank=True, null=True,
                upload_to=geoindodata.core.utils.FilenameGenerator(prefix='regencies')),
        ),
    ]
