# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.11
        architecture: x64


    - name: Restore pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --exists-action w
        pip install mypy==1.10.0
        pip install flake8

    - name: Mypy Tests
      run: |
        export DIFF_FILES=$(git diff --name-only --diff-filter=ACM $(git merge-base HEAD origin/master) | grep "\.py" | grep -v "settings" | grep -v "migrations")
        if [[ ! -z $DIFF_FILES ]]
        then
          echo "[MYPY] Checking ..." $DIFF_FILES
          mypy $DIFF_FILES --ignore-missing-imports --disallow-untyped-defs --allow-redefinition --follow-imports silent
        fi

    - name: Flake8 Tests
      run: |
        export DIFF_FILES=$(git diff --name-only --diff-filter=ACM $(git merge-base HEAD origin/master) | grep ".py")
        if [[ ! -z $DIFF_FILES ]]
        then
          echo "[Flake8] Checking ..." $DIFF_FILES
          flake8 $DIFF_FILES --exclude migrations,libraries,settings.py --ignore=W504 --max-line-length=120
        fi
